In [63]:
import numpy as np
import pandas as pd

In [93]:
df = pd.read_csv('fraudTrain.csv')
ft = pd.read_csv('fraudTest.csv')
ft1 = pd.read_csv('fraudTest.csv')

In [94]:
df.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [95]:
ft.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0

In [96]:
ft1.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0

In [97]:
df.shape

(1296675, 23)

In [98]:
ft.shape

(555719, 23)

In [99]:
ft1.shape

(555719, 23)

In [100]:
df.nunique()

Unnamed: 0               1296675
trans_date_trans_time    1274791
cc_num                       983
merchant                     693
category                      14
amt                        52928
first                        352
last                         481
gender                         2
street                       983
city                         894
state                         51
zip                          970
lat                          968
long                         969
city_pop                     879
job                          494
dob                          968
trans_num                1296675
unix_time                1274823
merch_lat                1247805
merch_long               1275745
is_fraud                       2
dtype: int64

In [101]:
ft.nunique()

Unnamed: 0               555719
trans_date_trans_time    544760
cc_num                      924
merchant                    693
category                     14
amt                       37256
first                       341
last                        471
gender                        2
street                      924
city                        849
state                        50
zip                         912
lat                         910
long                        910
city_pop                    835
job                         478
dob                         910
trans_num                555719
unix_time                544760
merch_lat                546490
merch_long               551770
is_fraud                      2
dtype: int64

In [102]:
ft1.nunique()

Unnamed: 0               555719
trans_date_trans_time    544760
cc_num                      924
merchant                    693
category                     14
amt                       37256
first                       341
last                        471
gender                        2
street                      924
city                        849
state                        50
zip                         912
lat                         910
long                        910
city_pop                    835
job                         478
dob                         910
trans_num                555719
unix_time                544760
merch_lat                546490
merch_long               551770
is_fraud                      2
dtype: int64

In [103]:
print('Total 0 in is_fraud: {}'.format(len(df[df['is_fraud'] == 0])))
print('Total 1 in is_fraud: {}'.format(len(df[df['is_fraud'] == 1])))

Total 0 in is_fraud: 1289169
Total 1 in is_fraud: 7506

In [104]:
print('Total 0 in is_fraud: {}'.format(len(ft[ft['is_fraud'] == 0])))
print('Total 1 in is_fraud: {}'.format(len(ft[ft['is_fraud'] == 1])))

Total 0 in is_fraud: 553574
Total 1 in is_fraud: 2145

In [105]:
print('Total 0 in is_fraud: {}'.format(len(ft1[ft1['is_fraud'] == 0])))
print('Total 1 in is_fraud: {}'.format(len(ft1[ft1['is_fraud'] == 1])))

Total 0 in is_fraud: 553574
Total 1 in is_fraud: 2145

In [106]:
df.isnull().sum()

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

In [107]:
ft.isnull().sum()

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

In [108]:
ft1.isnull().sum()

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

In [109]:
# Removed columns name
# Unnamed

In [110]:
df = df[['first','last','gender','dob','street','city','state','zip','lat','long','city_pop','job','trans_date_trans_time','trans_num','amt','unix_time','merchant','category','merch_lat','merch_long','is_fraud']]
ft = ft[['first','last','gender','dob','street','city','state','zip','lat','long','city_pop','job','trans_date_trans_time','trans_num','amt','unix_time','merchant','category','merch_lat','merch_long','is_fraud']]
ft1 = ft1[['first','last','gender','dob','street','city','state','zip','lat','long','city_pop','job','trans_date_trans_time','trans_num','amt','unix_time','merchant','category','merch_lat','merch_long','is_fraud']]

In [111]:
df.head()

,first,last,gender,dob,street,city,state,zip,lat,long,...,job,trans_date_trans_time,trans_num,amt,unix_time,merchant,category,merch_lat,merch_long,is_fraud
0,Jennifer,Banks,F,1988-03-09,561 Perry Cove,Moravian Falls,NC,28654,36.0788,-81.1781,...,"Psychologist, counselling",2019-01-01 00:00:18,0b242abb623afc578575680df30655b9,4.97,1325376018,"fraud_Rippin, Kub and Mann",misc_net,36.011293,-82.048315,0
1,Stephanie,Gill,F,1978-06-21,43039 Riley Greens Suite 393,Orient,WA,99160,48.8878,-118.2105,...,Special educational needs teacher,2019-01-01 00:00:44,1f76529f8574734946361c461b024d99,107.23,1325376044,"fraud_Heller, Gutmann and Zieme",grocery_pos,49.159047,-118.186462,0
2,Edward,Sanchez,M,1962-01-19,594 White Dale Suite 530,Malad City,ID,83252,42.1808,-112.2620,...,Nature conservation officer,2019-01-01 00:00:51,a1a22d70485983eac12b5b88dad1cf95,220.11,1325376051,fraud_Lind-Buckridge,entertainment,43.150704,-112.154481,0
3,Jeremy,White,M,1967-01-12,9443 Cynthia Court Apt. 038,Boulder,MT,59632,46.2306,-112.1138,...,Patent attorney,2019-01-01 00:01:16,6b849c168bdad6f867558c3793159a81,45.00,1325376076,"fraud_Kutch, Hermiston and Farrell",gas_transport,47.034331,-112.561071,0
4,Tyler,Garcia,M,1986-03-28,408 Bradley Rest,Doe Hill,VA,24433,38.4207,-79.4629,...,Dance movement psychotherapist,2019-01-01 00:03:06,a41d7549acf90789359a9aa5346dcb46,41.96,1325376186,fraud_Keeling-Crist,misc_pos,38.674999,-78.632459,0

In [112]:
ft.head()

,first,last,gender,dob,street,city,state,zip,lat,long,...,job,trans_date_trans_time,trans_num,amt,unix_time,merchant,category,merch_lat,merch_long,is_fraud
0,Jeff,Elliott,M,1968-03-19,351 Darlene Green,Columbia,SC,29209,33.9659,-80.9355,...,Mechanical engineer,2020-06-21 12:14:25,2da90c7d74bd46a0caf3777415b3ebd3,2.86,1371816865,fraud_Kirlin and Sons,personal_care,33.986391,-81.200714,0
1,Joanne,Williams,F,1990-01-17,3638 Marsh Union,Altonah,UT,84002,40.3207,-110.4360,...,"Sales professional, IT",2020-06-21 12:14:33,324cc204407e99f51b0d6ca0055005e7,29.84,1371816873,fraud_Sporer-Keebler,personal_care,39.450498,-109.960431,0
2,Ashley,Lopez,F,1970-10-21,9333 Valentine Point,Bellmore,NY,11710,40.6729,-73.5365,...,"Librarian, public",2020-06-21 12:14:53,c81755dbbbea9d5c77f094348a7579be,41.28,1371816893,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,40.495810,-74.196111,0
3,Brian,Williams,M,1987-07-25,32941 Krystal Mill Apt. 552,Titusville,FL,32780,28.5697,-80.8191,...,Set designer,2020-06-21 12:15:15,2159175b9efe66dc301f149d3d5abf8c,60.05,1371816915,fraud_Haley Group,misc_pos,28.812398,-80.883061,0
4,Nathan,Massey,M,1955-07-06,5783 Evan Roads Apt. 465,Falmouth,MI,49632,44.2529,-85.0170,...,Furniture designer,2020-06-21 12:15:17,57ff021bd3f328f8738bb535c302a31b,3.19,1371816917,fraud_Johnston-Casper,travel,44.959148,-85.884734,0

In [113]:
ft1.head()

,first,last,gender,dob,street,city,state,zip,lat,long,...,job,trans_date_trans_time,trans_num,amt,unix_time,merchant,category,merch_lat,merch_long,is_fraud
0,Jeff,Elliott,M,1968-03-19,351 Darlene Green,Columbia,SC,29209,33.9659,-80.9355,...,Mechanical engineer,2020-06-21 12:14:25,2da90c7d74bd46a0caf3777415b3ebd3,2.86,1371816865,fraud_Kirlin and Sons,personal_care,33.986391,-81.200714,0
1,Joanne,Williams,F,1990-01-17,3638 Marsh Union,Altonah,UT,84002,40.3207,-110.4360,...,"Sales professional, IT",2020-06-21 12:14:33,324cc204407e99f51b0d6ca0055005e7,29.84,1371816873,fraud_Sporer-Keebler,personal_care,39.450498,-109.960431,0
2,Ashley,Lopez,F,1970-10-21,9333 Valentine Point,Bellmore,NY,11710,40.6729,-73.5365,...,"Librarian, public",2020-06-21 12:14:53,c81755dbbbea9d5c77f094348a7579be,41.28,1371816893,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,40.495810,-74.196111,0
3,Brian,Williams,M,1987-07-25,32941 Krystal Mill Apt. 552,Titusville,FL,32780,28.5697,-80.8191,...,Set designer,2020-06-21 12:15:15,2159175b9efe66dc301f149d3d5abf8c,60.05,1371816915,fraud_Haley Group,misc_pos,28.812398,-80.883061,0
4,Nathan,Massey,M,1955-07-06,5783 Evan Roads Apt. 465,Falmouth,MI,49632,44.2529,-85.0170,...,Furniture designer,2020-06-21 12:15:17,57ff021bd3f328f8738bb535c302a31b,3.19,1371816917,fraud_Johnston-Casper,travel,44.959148,-85.884734,0

In [114]:
# columns operaton with different methods
# first- remove
# last- remove
# gender- LabelEncoder
# dob- remove
# street- remove
# city- LabelEncoder
# state- LabelEncoder
# zip- no change
# lat- remove
# long- remove
# city_pop- remove
# job- LabelEncoder
# trans_date_trans_time- remove
# trans_num- remove
# amt- no change
# unix_time- remove
# merchant- remove
# category- LabelEncoder
# merch_lat- remove
# merch_long- remove
# is_fraud- output

In [115]:
df = df[['amt','gender','city','state','zip','job','category','is_fraud']]
ft = ft[['amt','gender','city','state','zip','job','category','is_fraud']]
ft1 = ft1[['amt','gender','city','state','zip','job','category','is_fraud']]

In [116]:
df.head()

,amt,gender,city,state,zip,job,category,is_fraud
0,4.97,F,Moravian Falls,NC,28654,"Psychologist, counselling",misc_net,0
1,107.23,F,Orient,WA,99160,Special educational needs teacher,grocery_pos,0
2,220.11,M,Malad City,ID,83252,Nature conservation officer,entertainment,0
3,45.00,M,Boulder,MT,59632,Patent attorney,gas_transport,0
4,41.96,M,Doe Hill,VA,24433,Dance movement psychotherapist,misc_pos,0

In [139]:
for i in range(ft1['is_fraud'].shape[0]):
    if ft1['is_fraud'][i]==1:
        print(i)

1685
1767
1781
1784
1857
1891
1906
1956
1968
2026
2039
2173
2195
2258
2467
2495
2506
2650
5669
5757
5940
6023
10036
10047
10167
10193
10206
11666
11669
11702
11710
11770
11780
11789
11799
11831
11842
13345
13741
13806
13876
13897
14043
14064
14386
14678
15411
16050
16078
16155
16196
16229
16231
16326
16365
16442
16575
17711
18142
18458
18487
18509
18534
18537
18572
18885
19034
19392
21721
21747
21937
21953
22015
22087
22236
22256
22353
22379
22427
22547
23015
23216
24869
25792
25893
25921
25997
26013
26055
26088
26098
26139
26160
26161
26163
26194
26219
26231
26239
26363
26379
26397
26446
26466
26477
26519
26567
26586
26602
26607
26615
26633
26673
26696
26780
26825
27436
27783
28628
29120
29593
29664
29716
29765
29795
29859
29894
29895
29896
29912
30007
30010
30019
30289
31084
31806
32204
33880
33975
34001
34093
34114
34665
36033
36057
36082
36108
36126
36135
36143
36149
36187
36329
36334
36461
36476
36571
37051
38397
38527
38530
38598
38714
38779
38903
38962
39009
39021
40837
41719
41762
41808
41887
41925
41948
42139
42180
42194
42208
42415
42422
42505
42537
42550
45204
45810
45851
45888
45927
46031
46152
46303
46448
46621
46652
47434
48140
48991
49834
50228
50266
50722
50801
51722
51726
51736
51781
51809
51849
51879
51948
52029
53502
53893
54045
55462
55997
56269
56279
56317
56343
56359
56406
56435
56494
56543
56556
56608
56687
56690
56694
56699
56712
56745
58564
58565
58582
58596
58668
58707
58731
58743
58744
58772
58942
58974
58990
59081
59141
59231
59521
60228
60587
60747
61863
61951
61958
62003
62042
62064
62070
62129
62135
62150
62154
62363
62515
64637
65853
65904
65920
66096
66141
66193
66428
69793
69850
69858
70197
71440
71725
76277
76377
76545
77563
77911
78185
78315
78329
78331
78379
78434
78505
78603
78682
78683
78804
78846
78851
78873
78966
79083
79834
80749
81469
81647
81662
81684
81697
81702
81715
81731
81736
81752
81757
81775
81833
81835
81839
81861
81872
81909
81937
81960
81979
81992
82009
82020
82124
82125
82203
82387
82388
84649
85650
85656
85669
85670
85686
85691
85700
85715
85764
85779
85854
85863
85879
85897
85908
85967
86000
86102
86124
86150
86261
86283
86348
86373
88338
89628
89644
89757
89772
89798
89849
89926
89934
89939
90006
90012
90114
90132
90156
90175
90178
90406
91393
91637
91664
91705
91711
91774
91852
91979
92597
93626
93670
93728
93751
93774
93776
94056
94160
96065
96146
96153
96226
98257
98421
98451
98542
98912
100774
101578
101608
101614
101635
101689
101739
101773
101783
101786
101821
101988
102606
105325
105468
105539
105671
105811
105983
106092
106099
106121
106588
109452
109499
109514
109575
109706
111579
111635
111666
112251
112806
113411
113423
113452
113491
113541
113580
113606
113676
113702
113754
113846
113889
114560
115753
115796
115798
115852
115880
115884
116112
118000
118079
118128
118168
118212
118262
118271
118300
118492
118522
118526
121034
121313
121318
121382
121416
121451
121471
121552
121572
121745
121750
121752
121773
121836
121860
121880
121888
121895
121955
121975
121988
122036
122072
122149
122750
122886
123376
124735
125397
125489
125496
125527
125530
125550
125586
125628
125646
125853
125868
125872
125901
125915
125930
126100
126146
126155
126229
126233
128477
129229
129233
129238
129296
129306
129344
129480
129504
129700
129756
130108
130218
131183
131235
131272
131361
131376
131434
131478
131487
131535
131562
131567
131610
131866
133024
133268
133275
133300
133310
133415
133465
133471
133485
133518
133583
133590
133594
133599
133629
133660
133665
133672
133679
133681
133686
133691
133756
133781
133943
134048
134348
134726
135054
135278
135478
135551
135555
135604
135610
135622
135654
135676
135723
135726
135733
135742
135761
135773
135787
135808
135840
135849
135973
135977
135983
135993
135994
135996
136025
136032
136086
136102
136114
136138
136481
137758
137935
137946
137951
137964
137984
137986
137994
138063
138072
138152
138172
138234
138357
138440
138539
138644
141467
141558
141587
141602
141633
141703
141890
142143
142661
144024
145304
145308
145575
145655
145706
145731
145808
145955
146034
146158
146170
146491
147273
149101
149124
149190
149204
149260
149290
149298
149303
149310
149414
149418
149426
149479
149576
149591
149596
149668
149691
149744
149745
149759
151221
151230
151253
151261
151294
151306
151308
151313
151364
151376
151391
151501
151527
151528
152374
152435
153066
153228
153255
153285
153290
153319
153337
153346
153354
153430
153554
153648
154719
155506
155665
155849
157725
157874
158061
158072
158127
158285
159549
161507
161525
164771
164842
164859
165199
165207
165590
167837
167875
167913
168603
168609
168672
168825
168842
170770
170822
170960
171009
171129
171134
171701
171881
171976
172524
172543
172831
172857
172868
172917
172967
172968
172986
172989
173022
173105
173134
173306
173606
173612
174773
175150
175192
175260
175284
175318
175344
175434
175454
175472
177425
177464
177567
177611
177640
177799
178388
179846
180527
180683
180711
180729
180799
180874
180884
180908
180938
180944
181051
181115
181182
181348
181415
181509
183979
184565
184612
184715
184748
184762
184773
184899
184904
184940
184954
185049
185064
185072
185123
185168
185200
185205
185216
185234
185348
185387
186741
187315
188369
188430
188453
188475
188487
188504
188526
188543
188601
188602
188611
188648
188663
188736
188814
188846
188862
188911
189234
189240
189523
189565
189658
190458
190468
190512
190529
190583
190587
190670
190676
190806
190819
190829
190876
191404
191445
192352
192439
192464
192525
192564
192569
192570
192582
192590
192597
192598
192610
192734
192854
192999
194117
194209
194858
194922
194930
194943
194946
197574
197591
199625
200268
200283
200412
200745
204438
204528
204641
204693
204807
205370
205865
206067
206608
207509
207923
208262
208296
208298
208303
208454
208602
208615
208978
209869
209895
209899
209928
209951
209992
210230
211588
211624
211707
211725
211731
211823
211844
211899
211913
211946
211977
212009
212163
212212
213070
213322
213485
213498
213499
213509
213577
213620
213641
213669
213745
213814
213851
213855
213879
213882
213887
214610
215365
215400
215405
215436
215450
215455
215462
215492
215500
215522
215528
215536
215538
215557
215571
215776
215843
215900
215909
216330
216395
217750
218014
218022
218061
218091
218136
218302
218326
218470
218498
218538
218647
220616
220933
221271
221309
221343
221417
221429
221520
221560
221629
221700
221850
221854
221903
221912
223930
224153
224253
224257
224279
224287
224319
224381
224383
224536
224548
224615
225618
225872
225904
225951
225963
225984
226013
226149
226226
226242
227636
227707
227708
227742
227811
227823
227886
227930
228030
228067
228148
229460
229655
229995
231526
231616
231836
232024
233400
233703
234236
234288
234314
234326
234401
234446
234478
234488
234495
234563
234617
236148
236567
236700
237208
237592
237627
237664
237667
237784
238491
240652
240694
240721
240868
240891
240912
240921
241078
241079
241342
241370
241720
242018
242115
242194
242213
242388
242414
242415
242442
242448
242577
242587
242771
243321
243919
243924
243935
243950
243966
243997
244011
244170
244738
245274
245836
245857
245890
245895
248661
250394
250690
250930
251279
251581
253587
253809
253829
253900
253916
255297
256284
256535
256612
256626
256631
256714
256862
256873
256888
256926
256937
257242
257280
257810
257885
258083
258088
258100
258142
258150
258178
258185
258200
258234
258237
258241
258249
258250
258299
258307
258413
258431
258453
258455
258990
259778
259794
259802
259804
259810
259812
259815
259820
259828
259834
259869
259889
259900
259908
259916
259926
259965
259969
260010
260078
260134
260176
260192
261639
261643
261676
261717
261735
261766
261788
261792
261802
261814
261829
261997
262034
262538
263369
263727
263771
263851
263855
263982
264016
265219
265486
266160
266177
266186
266203
266229
266280
266285
266349
266366
266381
266419
266436
266495
266511
266753
267119
267729
267836
268392
269376
269380
269441
269451
269483
269493
269543
269898
270045
270178
270825
272370
272482
272502
272580
272942
273050
273950
274054
274086
274143
274154
274178
275747
275750
275753
275765
275829
275898
275972
277679
277718
277746
277800
277804
277932
277952
278017
278884
278913
279512
279520
279522
279571
279580
279644
279654
279658
279671
279725
279794
279805
279807
279878
279936
280025
280035
280063
280194
280222
281220
281309
281738
281965
282186
282204
282220
282223
282235
282237
282251
282264
282266
282268
282280
282286
282311
282313
282314
282317
282322
282349
282353
282389
282396
282410
282450
282467
282468
282530
282558
282565
282599
282601
282613
282614
282836
282848
283422
283496
283644
283708
283865
284199
284389
285363
285371
285393
285433
285456
285459
285474
285494
285507
285522
285557
285565
285608
285616
285649
285745
285852
285963
287536
288402
288413
288420
288426
288442
288481
288490
288508
288526
288556
288607
288690
288755
288763
288766
288819
289255
289494
289781
290070
290084
290093
290102
290124
290150
290196
290263
290316
290381
290431
291377
291576
291704
291714
291732
291752
291763
291797
291823
291839
292616
293570
293629
293670
294754
294905
295500
295510
295559
295584
295650
295689
295700
295818
295962
296012
296141
296761
297159
297808
297889
298141
298302
298311
298358
298434
298808
300776
301032
301324
301363
301389
301402
301528
301600
301866
301881
304225
304345
304350
304567
304640
304726
304738
304804
305209
305454
305498
305575
305879
306025
306031
306087
306117
306120
306123
306128
306156
306195
306208
306215
306221
306232
306258
306264
306270
306277
306328
306337
306386
306516
307561
307710
307720
307743
307744
307759
307760
307779
307794
307797
307818
307849
307854
307868
307982
307984
307989
307992
307993
308006
308053
308056
308080
308119
309296
309627
309659
309661
309666
309688
309694
309725
309787
309792
309937
309948
309991
310013
310014
310093
311149
311493
311494
311514
311523
311572
311582
311586
311628
311631
311656
311682
311726
311753
311780
311805
312276
313184
313436
313791
313910
314106
314113
314178
314222
314232
314240
314330
314352
314371
314605
316529
317299
322184
322331
322372
323545
323807
323855
323884
323962
325721
325873
325896
325967
327076
327216
327231
327375
327423
327427
327431
327439
327451
327456
327480
327530
327564
327598
327605
327627
327652
327686
327755
327826
327881
328127
328163
328192
328235
328867
329471
329800
329837
329986
330003
330010
330022
330048
330061
330087
330090
330093
330124
330135
330144
330173
330182
330196
330197
330212
330223
330237
330255
330260
330355
333143
333221
333419
333532
333551
334064
336070
336442
336477
336513
336518
336538
336601
336763
336809
337088
338026
338048
338205
338344
339404
339753
339829
341702
341754
341779
341783
341816
341919
342954
343387
343441
343443
343450
343479
343516
343555
343566
343617
343619
343667
343702
343708
343752
343823
343849
343850
345776
346024
346030
346138
346223
346389
347324
349069
349364
349415
349662
350057
351609
352237
352431
352497
352508
352551
352574
352614
352617
352634
352661
353359
353428
353895
353915
353958
353994
354001
354008
354010
354011
354058
354097
354117
354131
354134
354225
354254
354302
354356
354692
355331
355523
355529
355534
355558
355564
355612
355655
355667
355690
355744
355852
355870
357074
357366
357378
357473
357702
358852
358984
359215
359331
359475
359492
359495
359538
359720
361291
361301
361853
361904
361911
362054
362088
362137
362774
364289
365378
365424
365436
365495
365603
365644
365850
368366
368370
368372
368457
368503
368507
368558
368573
368623
368654
370092
370109
370156
370372
370377
370835
371703
371721
371801
371808
371812
371874
371875
371943
371964
372012
372370
373523
373526
373553
373557
373615
373617
373643
373809
373934
374050
375337
375355
375443
375565
375756
377814
378097
378167
378175
378263
378437
378438
378618
378740
381178
384711
384716
385753
385844
385859
385901
385945
385961
385968
386034
386082
386096
386097
386172
386289
386313
387443
387490
387556
387559
387605
387610
387625
387658
387697
387752
387816
387823
387845
387900
387908
387910
388332
389126
389218
389332
389344
389348
389352
389358
389360
389373
389394
389396
389445
389704
390207
391121
391235
391248
391272
391291
391528
393624
393745
394134
394148
394245
396826
396866
396898
397032
397066
397472
399919
400054
400174
400197
400243
400263
400298
400331
400353
400646
401045
401268
401448
401559
401582
401588
401623
401625
401637
401640
401695
401705
401724
401765
401780
401785
401795
401805
401950
402308
402422
402489
402668
402960
402991
403057
403183
403193
403216
403231
403234
403235
403249
403254
403258
403272
403273
403304
403329
403353
403381
403438
403491
403525
403549
403574
403838
403928
404444
404678
405004
405012
405025
405026
405027
405039
405047
405098
405115
405159
405160
405162
405191
405252
405408
406515
406757
406811
406846
406887
416202
416421
416511
416652
416892
416981
417010
417140
421290
421833
421949
422405
422683
422759
425118
425120
425124
425150
425162
425166
425170
425171
425181
425184
425205
425220
425245
425405
425459
428496
428593
428902
429206
431889
432006
432147
432168
432176
432283
432375
432481
432545
432643
432709
432746
433126
435333
435757
435862
435973
436071
436087
436106
436151
436264
436487
436725
438561
438819
440768
441000
441001
441008
441072
441151
441283
441292
441315
441421
441426
441467
441835
442126
442214
447199
447469
447559
447639
447696
447759
447769
447897
448224
448229
448527
448589
448652
448694
448745
448758
448786
448840
448848
448892
449117
449411
450096
450958
453516
453559
453573
453617
453662
453717
453728
453869
453937
453968
454063
454114
454170
454189
454312
454521
454568
454943
455040
456449
456761
456922
456964
457053
457100
457111
457136
457409
457517
459494
460566
460624
460726
460735
460836
460882
460883
460892
460924
461013
461095
461105
461106
461263
462194
462378
462762
464104
464119
464229
464284
464351
464428
464440
464451
464452
464483
464493
464505
464569
464635
464810
465956
466344
467238
467434
467739
467781
467904
467970
468012
468152
468426
471208
472941
473010
473095
473151
473228
473378
473720
473849
474056
474087
474131
476145
479206
479216
479321
479443
479444
479884
480010
480500
480763
483521
485148
485390
485393
485405
485605
485616
485783
485859
485998
486051
486094
488646
488648
488657
488684
488699
488786
488792
488869
488895
488998
489181
489185
491539
491777
492026
492082
492141
492158
492197
492200
492277
492284
495154
495791
495812
496197
496267
497523
499585
499719
499732
499789
501393
504945
505085
505195
505352
505711
505774
505826
506021
511235
511244
511272
511374
511675
512502
514913
517197
517274
517341
517529
517571

In [150]:
print(ft['amt'][1685])
print(ft['gender'][1685])
print(ft['city'][1685])
print(ft['state'][1685])
print(ft['zip'][1685])
print(ft['job'][1685])
print(ft['category'][1685])
print(ft['is_fraud'][1685])

24.84
0
557
42
779
109
5
1

In [117]:
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()
df['gender'] = LE.fit_transform(df['gender'])
df['city'] = LE.fit_transform(df['city'])
df['state'] = LE.fit_transform(df['state'])
df['zip'] = LE.fit_transform(df['zip'])
df['job'] = LE.fit_transform(df['job'])
df['category'] = LE.fit_transform(df['category'])

In [118]:
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()
ft['gender'] = LE.fit_transform(ft['gender'])
ft['city'] = LE.fit_transform(ft['city'])
ft['state'] = LE.fit_transform(ft['state'])
ft['zip'] = LE.fit_transform(ft['zip'])
ft['job'] = LE.fit_transform(ft['job'])
ft['category'] = LE.fit_transform(ft['category'])

In [119]:
X = df.iloc[:,:-1]
Y = df.iloc[:,-1]

In [147]:
X1 = ft.iloc[:,:-1]
Y1 = ft.iloc[:,-1]
X1

           amt  gender  city  state  zip  job  category
0         2.86       1   157     39  254  275        10
1        29.84       0    16     43  811  392        10
2        41.28       0    61     33   69  259         5
3        60.05       1   764      8  291  407         9
4         3.19       1   247     21  478  196        13
...        ...     ...   ...    ...  ...  ...       ...
555714   43.77       1   443     23  618  460         5
555715  111.84       1   401     42  763  198         7
555716   86.88       0   104     46  908  294         7
555717    7.99       1   476     12  808   58        13
555718   38.13       1   224     35  706  276         0

[555719 rows x 7 columns]

In [121]:
X2 = ft1.iloc[:,:-1]
Y2 = ft1.iloc[:,-1]

## Logistic Regression

In [125]:
from sklearn.linear_model import LogisticCl
from sklearn.metrics import accuracy_score
LR = LogisticRegression(max_iter=1000)
LR.fit(X,Y)
Y_pred = LR.predict(X1)
accuracy_score(Y1,Y_pred)

## Decision Tree

In [153]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import r2_score
DT = DecisionTreeClassifier()
DT.fit(X,Y)
Y_pred = DT.predict(X1)
r2_score(Y1,Y_pred)

-0.08249998149343196

## Random Forest

In [154]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import r2_score
RF = RandomForestClassifier(n_estimators=50)
RF.fit(X,Y)
RF.predict([[620.33,1,64,47,515,367,0]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array([1], dtype=int64)

In [156]:
# RF.predict([[24.84,0,557,42,779,109,5]])
# 2.86,1,157,39,254,275,10
y_pred=RF.predict(X1)
r2_score(Y1,y_pred)

0.37801881737796317

## Navie Bayes

In [36]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
NB = GaussianNB()
NB.fit(X,Y)
y_pred = NB.predict(X1)
accuracy_score(Y1,y_pred)

0.992073332025718

In [37]:
import pickle
pickle.dump(df,open('CreditCardFraud.pkl','wb'))

In [127]:
import pickle
pickle.dump(ft1,open('TestCreditCardFraud.pkl','wb'))